views:
  - title: SunPower
    autor: StepSolar
    theme: Google Light and Dark Theme
    path: floorplan
    panel: true
    type: panel
    cards:
      - config:
          image:
            location: /local/floorplan/solar/panelsunpower.svg
          rules:
            - name: wattpower1
              element: wattpanel1
              entity: sensor.power_1_1_1
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "w"}
            - name: whpower1
              element: whpanel1
              entity: sensor.panel_1_oggi
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "wh"}
            - name: wattpower2
              element: wattpanel2
              entity: sensor.power_1_1_2
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "w"}
            - name: whpower2
              element: whpanel2
              entity: sensor.panel_2_oggi
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "wh"}
            - name: wattpower3
              element: wattpanel3
              entity: sensor.power_1_1_3
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "w"}
            - name: whpower3
              element: whpanel3
              entity: sensor.panel_3_oggi
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "wh"}
            - name: wattpower4
              element: wattpanel4
              entity: sensor.power_1_1_4
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "w"}
            - name: whpower4
              element: whpanel4
              entity: sensor.panel_4_oggi
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "wh"}
            - name: wattpower5
              element: wattpanel5
              entity: sensor.power_1_1_5
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "w"}
            - name: whpower5
              element: whpanel5
              entity: sensor.panel_5_oggi
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "wh"}
            - name: wattpower6
              element: wattpanel6
              entity: sensor.power_1_1_6
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "w"}
            - name: whpower6
              element: whpanel6
              entity: sensor.panel_6_oggi
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "wh"}
            - name: wattpower7
              element: wattpanel7
              entity: sensor.power_1_1_7
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "w"}
            - name: whpower7
              element: whpanel7
              entity: sensor.panel_7_oggi
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "wh"}
            - name: wattpower8
              element: wattpanel8
              entity: sensor.power_1_1_8
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "w"}
            - name: whpower8
              element: whpanel8
              entity: sensor.panel_8_oggi
              state_action:
                action: call-service
                service: floorplan.text_set
                service_data: ${(entity.state) + "wh"}
            - name: panel1
              element: colorblu1
              entity: sensor.power_1_1_1
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: >
                    > var temp = parseFloat(entity.state);  if (temp <= 50)
                    return "fill: #02070C";  else if (temp <= 70) return "fill:
                    #071626"; else if (temp <= 100) return "fill: #0C263F"; else
                    if (temp <= 150) return "fill: #194C7F"; else if (temp <=
                    170) return "fill: #1E5B99"; else if (temp <= 200) return
                    "fill: #2163A5"; else if (temp <= 250) return "fill:
                    #2672BF"; else return "fill: #2D89E5";
            - name: panel2
              element: colorblu2
              entity: sensor.power_1_1_2
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: >
                    > var temp = parseFloat(entity.state);  if (temp <= 50)
                    return "fill: #02070C";  else if (temp <= 70) return "fill:
                    #071626"; else if (temp <= 100) return "fill: #0C263F"; else
                    if (temp <= 150) return "fill: #194C7F"; else if (temp <=
                    170) return "fill: #1E5B99"; else if (temp <= 200) return
                    "fill: #2163A5";  else if (temp <= 250) return "fill:
                    #2672BF";  else if (temp <= 280) return "fill: #2D89E5";
                    else return "fill: #3091F2";
            - name: panel3
              element: colorblu3
              entity: sensor.power_1_1_3
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: >
                    > var temp = parseFloat(entity.state);  if (temp <= 50)
                    return "fill: #02070C";  else if (temp <= 70) return "fill:
                    #071626"; else if (temp <= 100) return "fill: #0C263F"; else
                    if (temp <= 150) return "fill: #194C7F"; else if (temp <=
                    170) return "fill: #1E5B99"; else if (temp <= 200) return
                    "fill: #2163A5"; else if (temp <= 250) return "fill:
                    #2672BF"; else if (temp <= 280) return "fill: #2D89E5"; else
                    return "fill: #3091F2";
            - name: panel4
              element: colorblu4
              entity: sensor.power_1_1_4
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: >
                    > var temp = parseFloat(entity.state);  if (temp <= 50)
                    return "fill: #02070C";  else if (temp <= 70) return "fill:
                    #071626"; else if (temp <= 100) return "fill: #0C263F"; else
                    if (temp <= 150) return "fill: #194C7F"; else if (temp <=
                    170) return "fill: #1E5B99"; else if (temp <= 200) return
                    "fill: #2163A5"; else if (temp <= 250) return "fill:
                    #2672BF"; else if (temp <= 280) return "fill: #2D89E5"; else
                    return "fill: #3091F2";
            - name: panel5
              element: colorblu5
              entity: sensor.power_1_1_5
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: >
                    > var temp = parseFloat(entity.state);  if (temp <= 50)
                    return "fill: #02070C";  else if (temp <= 70) return "fill:
                    #071626"; else if (temp <= 100) return "fill: #0C263F"; else
                    if (temp <= 150) return "fill: #194C7F"; else if (temp <=
                    170) return "fill: #1E5B99"; else if (temp <= 200) return
                    "fill: #2163A5"; else if (temp <= 250) return "fill:
                    #2672BF"; else if (temp <= 280) return "fill: #2D89E5"; else
                    return "fill: #3091F2";
            - name: panel6
              element: colorblu6
              entity: sensor.power_1_1_6
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: >
                    > var temp = parseFloat(entity.state);  if (temp <= 50)
                    return "fill: #02070C";  else if (temp <= 70) return "fill:
                    #071626"; else if (temp <= 100) return "fill: #0C263F"; else
                    if (temp <= 150) return "fill: #194C7F"; else if (temp <=
                    170) return "fill: #1E5B99"; else if (temp <= 200) return
                    "fill: #2163A5"; else if (temp <= 250) return "fill:
                    #2672BF"; else if (temp <= 280) return "fill: #2D89E5"; else
                    return "fill: #3091F2"; 
            - name: panel7
              element: colorblu7
              entity: sensor.power_1_1_7
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: >
                    > var temp = parseFloat(entity.state);  if (temp <= 50)
                    return "fill: #02070C";  else if (temp <= 70) return "fill:
                    #071626"; else if (temp <= 100) return "fill: #0C263F"; else
                    if (temp <= 150) return "fill: #194C7F"; else if (temp <=
                    170) return "fill: #1E5B99"; else if (temp <= 200) return
                    "fill: #2163A5"; else if (temp <= 250) return "fill:
                    #2672BF"; else if (temp <= 280) return "fill: #2D89E5"; else
                    return "fill: #3091F2";
            - name: panel8
              element: colorblu8
              entity: sensor.power_1_1_8
              state_action:
                action: call-service
                service: floorplan.style_set
                service_data:
                  style: >
                    > var temp = parseFloat(entity.state);  if (temp <= 50)
                    return "fill: #02070C";  else if (temp <= 70) return "fill:
                    #071626"; else if (temp <= 100) return "fill: #0C263F"; else
                    if (temp <= 150) return "fill: #194C7F"; else if (temp <=
                    170) return "fill: #1E5B99"; else if (temp <= 200) return
                    "fill: #2163A5"; else if (temp <= 250) return "fill:
                    #2672BF"; else if (temp <= 280) return "fill: #2D89E5"; else
                    return "fill: #3091F2";
          defaults:
            tap_action: more-info
          stylesheet: /local/floorplan/solar/panelsunpower.css
        full_height: true
        type: custom:floorplan-card

